### ISSUE TITLE
破壳遇到个问题.

### ISSUE THREAD

**Issue by windorz9** [smartdone/Frida-Scripts#14]
你好, 非常感谢提供破壳的解决方案, 第一次破壳应用(我是个菜鸟), 安装好 pip-> 手机解锁 -> root -> 启动 frida-server, 最后运行你的 unpack 脚本然后跑起来就报这个
Use %resume to let the main thread start executing!
我按照步骤敲 %resume 一直没反应 emm 就是一个无限循环, 可能我哪里搞错了, 然后看到你的另一个 issue 回答 在命令后加 --no-pause 就变成了下面这样.
Resuming main thread!
好像又没什么反应.
哪里出问题了呢?
测试手机红米6 安卓 8.1.0. 没有找到 7.0 的机子.

**Comment by smartdone** [comment]
8.1下面没有openmemory了 http://androidxref.com/8.1.0_r33/xref/art/runtime/dex_file.cc 
你可以试试下面这个函数
```c++
std::unique_ptr<DexFile> DexFile::OpenCommon(const uint8_t* base,
                                             size_t size,
                                             const std::string& location,
                                             uint32_t location_checksum,
                                             const OatDexFile* oat_dex_file,
                                             bool verify,
                                             bool verify_checksum,
                                             std::string* error_msg,
                                             VerifyResult* verify_result)
```

**Comment by windorz9** [comment]
emmm 这么快就回答了我, 有点惊讶, 非常感谢

**Comment by windorz9** [comment]
非常厚颜无耻的追问一下, 这个函数我有点不会用, 能不能麻烦你具体讲讲 orz

**Comment by windorz9** [comment]
再次厚着脸皮追问一下, 我找了一台 安卓 6.0.1 的手机测试出现了和 #13 同样的问题
Error: access violation accessing 0xf36ab000
    at [anon] (/repl1.js:77)
    at input:1

orz ...
