### ISSUE TITLE
**密使用无效,是使用方法不对么

### ISSUE THREAD

**Issue by liujianying** [smartdone/Frida-Scripts#3]
delalu:unpack liujianying$ frida -R -f com.aimobo.dynamic -l ./unpack.js
     ____
    / _  |   Frida 12.2.5 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Spawning `com.aimobo.dynamic`...
openmemory at0xf4e49991
Spawned `com.aimobo.dynamic`. Use %resume to let the main thread start executing!
[Remote::com.aimobo.dynamic]-> Process terminated
[Remote::com.aimobo.dynamic]->

Thank you for using Frida!
delalu:unpack liujianying$

**Comment by lonehand** [comment]
这边尝试脱ijiami的普通壳，执行会失败
![image](https://user-images.githubusercontent.com/20275278/45732652-df331b80-bc0f-11e8-96d8-763e8f740c4d.png)

**Comment by liujianying** [comment]
@lonehand  兄弟一起入坑了,我用没加密的app也是这样效果,感觉没用对啊

**Comment by smartdone** [comment]
看一下是不是这个问题
 1. 是不是x86模拟器，如果是模拟器，看apk是否支持x86的abi
2. apk支持x86的abi，看看是不是apk解压之后的libs下面x86的so是不是齐全的，要是x86的so比arm下面的少几个，也可能是不完全支持x86

要是是真机的话，把崩溃的日志发出来看一下下，我看看是什么问题

**Comment by lonehand** [comment]
apk的lib目录下没有x86，是这个原因么

**Comment by liujianying** [comment]
奔溃日志在哪里
