### ISSUE TITLE
无法连接远程 frida server

### ISSUE THREAD

**Issue by menglinxi** [smartdone/Frida-Scripts#5]
D:\crackapk>frida -R -f com.ssky.gamebox -l unpack.js
     ____
    / _  |   Frida 12.2.5 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to spawn: unable to connect to remote frida-server
这个错误是？
frida，安装在windows上。app安装在手机上。

**Comment by smartdone** [comment]
你frida-server启动了吗，27042端口转发了吗

**Comment by menglinxi** [comment]
我push了 frida-server到手机上了，然后 ./启动了，没有输出。端口转发了。

**Comment by menglinxi** [comment]
https://pan.baidu.com/s/13cDxgLLEwvECkb_9E7uRWQ 提取码: e3rs  麻烦帮忙看看，这个app能脱壳吗？
