### ISSUE TITLE
用你的脚本没法 脱壳

### ISSUE THREAD

**Issue by menglinxi** [smartdone/Frida-Scripts#6]
链接: https://pan.baidu.com/s/1XK1ng5FxjNGEe6r提取码: 求帮忙看看。

**Comment by smartdone** [comment]
可以脱掉啊 链接: https://pan.baidu.com/s/1i6exuxwZXfwV5JiLTQQEqQ 提取码: x4z6

**Comment by menglinxi** [comment]
感谢 博主。。。我今天又尝试了一次   
D:\crackapk>frida -R -f com.ssky.gamebox -l unpack.js
     ____
    / _  |   Frida 12.2.5 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to load script: gDBus.Error:re.frida.Error.InvalidArgument: Script(line 9): SyntaxError: parse error

Thank you for using Frida!
虽然，我自己没 脱壳成功。但是还是非常感谢博主，帮忙脱壳。
