### ISSUE TITLE
等待应用启动超时？

### ISSUE THREAD

**Issue by Holdmyhand** [smartdone/Frida-Scripts#9]
C:\Users\Holdmyhand\Desktop>frida -R -f com.xinyuanlinglai -l unpack.js
     ____
    / _  |   Frida 12.2.15 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Failed to spawn: unexpectedly timed out while waiting for app to launch

C:\Users\Holdmyhand\Desktop>
手机是小米的，安卓7.0，MIUI10  敲完命令后软件com.xinyuanlinglai能正常启动运行。

**Comment by smartdone** [comment]
这好像是frida的bug
